version: '3'

services:
  server:
    image: framefactory/node:latest
    container_name: remix-template-server
    restart: unless-stopped

    command: [ "npm", "run", "$NPM_SCRIPT" ]

    environment:
      - WATCH_COMPONENT
    env_file:
      - .env
    ports:
      - $DOCKER_SERVER_PORT:$DOCKER_SERVER_PORT
      - $DOCKER_SERVER_DEV_PORT:$DOCKER_SERVER_DEV_PORT
    volumes:
      - .:/app
    links:
      - db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:latest
    container_name: remix-template-db
    restart: unless-stopped

    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5

    env_file:
      - .env
    ports:
      - $DOCKER_DB_PORT:3306
    volumes:
      - ./services/db/data:/var/lib/mysql

  admin:
    image: phpmyadmin:latest
    container_name: remix-template-admin
    restart: unless-stopped

    env_file:
      - .env
    ports:
      - $DOCKER_ADMIN_PORT:80
    links:
      - db:mysql_db_server
    depends_on:
      - db

#volumes:
#  db_data: {}